---
#https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

- include_tasks: rhel.yml
  when: ansible_os_family == "RedHat"

- include_tasks: user.yml
  when: update_user_env | bool

- include_tasks: systemd.yml
  when: install_systemd_unit | bool
