---
- name: Verify kernel settings
  block:
    - name: Disabling Nouveau
      copy:
        src: blacklist-nouveau.conf
        dest: /usr/lib/modprobe.d/blacklist-nouveau.conf
        owner: root
        group: root
        mode: '0644'

    - name: Regenerate the kernel initramfs
      command: dracut --force

    - name: Verify the System has the Kernel Headers and Development Packages Installed
      package:
        name: "{{ packages }}"
        state: installed
      vars:
        packages:
          - kernel-devel
          - kernel-headers

- name: Set Cuda repositories for RHEL 7 and install it
  block:
    - name: Add Cuda gpg key (Centos 7)
      rpm_key:
        state: present
        key: "{{ cuda_rhel7_gpg_key }}"

    - name: Install cuda repository meta-data (Centos 7)
      package:
        name: "{{ cuda_rhel7_url }}"
        state: installed

    - name: Install CUDA (RHEL 7)
      package:
        name: "{{ cuda_rhel7_package_name }}"
        state: installed
        update_cache: true
      when: install_cuda | bool
  when: ansible_distribution_major_version | int == 7

- name: Set Cuda repositories for RHEL 8 and install it
  block:
    - name: Enable cuda repository meta-data (RHEL 8)
      ansible.builtin.command:
        cmd: "dnf config-manager --add-repo {{ cuda_rhel8_url }}"

    - name: Install CUDA (RHEL 8)
      package:
        name: "{{ cuda_rhel8_package_name }}"
        state: installed
        update_cache: true
      when: install_cuda | bool
  when: ansible_distribution_major_version | int == 8

- name: Set Cuda repositories for RHEL 9 and install it
  when: ansible_distribution_major_version | int == 9
  block:
    - name: Enable cuda repository meta-data (RHEL 9)
      ansible.builtin.command:
        cmd: "dnf config-manager --add-repo {{ cuda_rhel9_url }}"
    - name: Install CUDA (RHEL 9)
      ansible.builtin.package:
        name: "{{ cuda_rhel9_package_name }}"
        state: present
        update_cache: true
      when: install_cuda | bool
    - name: Update to latest nvidia driver
      ansible.builtin.dnf:
        name: '@nvidia-driver:latest-dkms'
        state: present
