---
- name: Update user environment setup
  lineinfile:
    path: "{{ user_profile_path }}"
    line: "{{ item }}"
  with_items:
    - "export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}"
    - "export LD_LIBRARY_PATH=/usr/local/cuda/lib ${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"
